### ISSUE TITLE
Make AMD compatible

### ISSUE THREAD

**Issue by willdady** [imhoffd/jquery-textrange#10]
Would be great if this registered itself as an AMD module so it can be loaded easily with requirejs. This could be achieved quite easily by wrapping the self-executing function in a simple conditional.

See:
http://stackoverflow.com/questions/10918063/how-to-make-a-jquery-plugin-loadable-with-requirejs#answer-11890239

**Comment by imhoffd** [comment]
Done! I will write up some documentation on how to require this plugin with requirejs.
