### ISSUE TITLE
Make UMD compatible

### ISSUE THREAD

**Issue by willdady** [imhoffd/jquery-textrange#12]
Can we get the newly added AMD style wrapper tweaked slightly so it becomes a UMD module. This will allow the plugin to be loaded in a CommonJS environment, specifically browserify/node.

See - https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

**Comment by imhoffd** [comment]
Yeah I saw that when making the AMD wrapper. Will update to be UMD compatible.
