### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by dgbeck** [imhoffd/jquery-textrange#16]
Hello,

Would like to use this great looking plugin with browserify / [cartero](https://github.com/rotundasoftware/cartero). Looks like you already have a UMD.. would you be so kind as to add package.json and publish to npm? Can do a PR if you'd like.

Thx!

David

**Comment by imhoffd** [comment]
Done!

https://www.npmjs.org/package/jquery-textrange

**Comment by dgbeck** [comment]
thx!
