### ISSUE TITLE
Is it possible to select the current word when click on word in textarea

### ISSUE THREAD

**Issue by gchokeen** [imhoffd/jquery-textrange#18]
Thanks for useful plugin!
I want to select whole word when I click on specific word. is it possible?

I have list of tags in my textarea content like <first_name>,<email> etc.  When user clicks on the tag. I want show the list of available to tags to the user. so when user selects the the tag from the list I simply want to replace. I can do most of the thinks using your plugin. But I don't know how to select the whole word when user simply clicks on the word in textarea.

Thanks

**Comment by imhoffd** [comment]
It's possible.

You have to use 'get' and then grab the content of your textarea as a string, looking on either side of the cursor location index within that string for spaces. Then just use 'set' on the range you determine.

Then use jquery for the events when a user clicks on the textarea.
