### ISSUE TITLE
Compatibility with TinyMCE 3?

### ISSUE THREAD

**Issue by tdm00** [imhoffd/jquery-textrange#3]
I'm using TinyMCE for a text area and I'm trying to grab the selected text within the TinyMCE editor to modify.  My `var range = $("#editor").textrange();` code keeps returning an object but the position, start, end and length are all 0 and text is blank.

**Comment by tdm00** [comment]
Sorry, it looks like TinyMCE has this capability already and I didn't know it.

``` javascript
// get the selected text in the editor
alert(tinymce.activeEditor.selection.getContent());

// replace the selected text with different text
alert(tinymce.activeEditor.selection.setContent('Ready for battle princess?'));
```

**Comment by imhoffd** [comment]
Typically I would not advise the use of this plugin with any WYSIWYG editors, as so much is going on within the actual editor. It's a bit out of scope for this jQuery plugin and as you found out many of the extensive editors have this functionality already.

**Comment by tdm00** [comment]
No idea, it's beyond my JavaScript skills at the moment. In any case, thanks for a great plugin.
