### ISSUE TITLE
Undo/Redo Issue

### ISSUE THREAD

**Issue by selvinortiz** [imhoffd/jquery-textrange#9]
Undo/Redo stops working after doing an **insert**, is there a way around this?

I have a `textarea` where text gets inserted into when a button is pressed via `textrange` but after the initial insert/replace, undo/redo no longer works on that textarea.

**Comment by imhoffd** [comment]
The insert is not a user action, it cannot be undone/redone. WYSIWYG editors handle this functionality by keeping a history of actions within the textarea and then capture a `CTRL+Z` key combination as an event and then act on that. But that doesn't solve the issue when users go to Edit -> Undo. Such editors pretty much have to override any and all undo/redo functionality, and that is outside the scope of this project.

Until there is better browser support for undo/redo, I can't add this functionality.

**Comment by selvinortiz** [comment]
Totally undestandable, thanks for the quick reply.

Cheers!
